# Site settings
title: Vaibhavi Pore
description: Vaibhavi Pore
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: https://vpore.github.io # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Vaibhavi Pore
user_description: 
user_title: MERN-stack Developer
email: porevaibhavi5@gmail.com
twitter_username: vaibhavi_pore
github_username:  vpore
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
